version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auto_ds
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run streamlit.py
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

volumes:
  db_data: